Add linter and confirmation to the release script. #7 #8

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -27,6 +27,15 @@ then
   exit 1
 fi
 
+echo "$ eslint --quiet src"
+eslint --quiet src
+
+if [ $? -ne 0 ]
+then
+  echo >&2 "Looks like there are linting errors. Make sure all errors are cleaned-up and run this script again."
+  exit 1
+fi
+
 echo "Existing releases:"
 git tag -l
 
@@ -41,6 +50,12 @@ sed -i.bak -E "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$version
 rm package.json.bak
 sed -i.bak -E "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$version\"/" bower.json
 rm bower.json.bak
+
+read -p "Are you sure you want to release v$version? (yes/no) " confirm
+if [ $confirm != "yes" ]
+then
+  exit 0
+fi
 
 echo "$ git add ."
 git add .
