Improve the test scripts & other tooling.

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,13 +1,11 @@
 #!/usr/bin/env bash
 
-if [ $(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/') != "master" ]
-then
+if [ $(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/') != "master" ]; then
   echo >&2 "Looks like you're not on the master branch. Checkout master and run this script."
   exit 1
 fi
 
-if [[ -n $(git status --porcelain 2> /dev/null) ]]
-then
+if [[ -n $(git status --porcelain 2> /dev/null) ]]; then
   echo >&2 "Looks like you're in a dirty head state. Clean-up un-committed files before and run this script again."
   exit 1
 fi
@@ -21,8 +19,7 @@ npm install
 echo "$ npm test"
 npm test
 
-if [ $? -ne 0 ]
-then
+if [ $? -ne 0 ]; then
   echo >&2 "Looks like there are failing tests. Make sure all tests pass and run this script again."
   exit 1
 fi
@@ -30,8 +27,7 @@ fi
 echo "$ eslint --quiet src"
 eslint --quiet src
 
-if [ $? -ne 0 ]
-then
+if [ $? -ne 0 ]; then
   echo >&2 "Looks like there are linting errors. Make sure all errors are cleaned-up and run this script again."
   exit 1
 fi
@@ -42,9 +38,9 @@ git tag -l
 read -p "Enter the version number for this release (eg '1.4.5'): " version
 
 echo "Building docs..."
-esdoc -c esdoc.json
+npm run docs
 echo "Building dist..."
-babel src/store.js -m umd --module-id Store --compact true --no-comments -o dist/store.js
+npm run build
 echo "Updating NPM and Bower manifests..."
 sed -i.bak -E "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$version\"/" package.json
 rm package.json.bak
@@ -52,8 +48,9 @@ sed -i.bak -E "s/\"version\": \"[0-9]+\.[0-9]+\.[0-9]+\"/\"version\": \"$version
 rm bower.json.bak
 
 read -p "Are you sure you want to release v$version? (yes/no) " confirm
-if [ $confirm != "yes" ]
-then
+
+if [ $confirm != "yes" ]; then
+  echo "Aborting."
   exit 0
 fi
 
